from app.config import DEFAULT_MAIL_SENDER, SMTP_PASSWORD, SMTP_PORT, SMTP_SERVER, SMTP_USERNAME, SMTP_USE_SSL, SMTP_USE_TLS


class MailConfig:
    MAIL_SERVER = SMTP_SERVER
    MAIL_PORT = int(SMTP_PORT or 587)
    MAIL_USE_TLS = SMTP_USE_TLS
    MAIL_USE_SSL = SMTP_USE_SSL
    MAIL_USERNAME = SMTP_USERNAME
    MAIL_PASSWORD = SMTP_PASSWORD
    MAIL_DEFAULT_SENDER = DEFAULT_MAIL_SENDER
