from app.config import DEFAULT_MAIL_SENDER, SMTP_PASSWORD, SMTP_PORT, SMTP_SERVER, SMTP_USERNAME


class MailConfig:
    MAIL_SERVER = SMTP_SERVER
    MAIL_PORT = int(SMTP_PORT or 587)
    MAIL_USE_TLS = True
    MAIL_USERNAME = SMTP_USERNAME
    MAIL_PASSWORD = SMTP_PASSWORD
    MAIL_DEFAULT_SENDER = DEFAULT_MAIL_SENDER
