from __future__ import annotations

CAMPAIGN_AUTOMATION_DISPATCH_ACTION = "dispatch_due_communications"
CAMPAIGN_AUTOMATION_LIFECYCLE_ACTION = "advance_lifecycle"

CAMPAIGN_AUTOMATION_EXECUTION_COMMUNICATION = "COMMUNICATION_DISPATCH"
CAMPAIGN_AUTOMATION_EXECUTION_LIFECYCLE = "LIFECYCLE_TRANSITION"

CAMPAIGN_AUTOMATION_STATUS_STARTED = "STARTED"
CAMPAIGN_AUTOMATION_STATUS_SUCCEEDED = "SUCCEEDED"
CAMPAIGN_AUTOMATION_STATUS_FAILED = "FAILED"
CAMPAIGN_AUTOMATION_STATUS_SKIPPED = "SKIPPED"
CAMPAIGN_AUTOMATION_STATUS_BLOCKED = "BLOCKED"

CAMPAIGN_DELIVERY_STATUS_SENT = "SENT"
CAMPAIGN_DELIVERY_STATUS_FAILED = "FAILED"
CAMPAIGN_DELIVERY_STATUS_SKIPPED = "SKIPPED"

CAMPAIGN_AUTOMATION_HEARTBEAT_KEY = "bt:campaigns:worker:last_heartbeat"
