from __future__ import annotations

CAMPAIGN_STATUS_DRAFT = "DRAFT"
CAMPAIGN_STATUS_ACTIVE = "ACTIVE"
CAMPAIGN_STATUS_CLOSED = "CLOSED"
CAMPAIGN_STATUS_ARCHIVED = "ARCHIVED"

CAMPAIGN_STATUSES = {
    CAMPAIGN_STATUS_DRAFT,
    CAMPAIGN_STATUS_ACTIVE,
    CAMPAIGN_STATUS_CLOSED,
    CAMPAIGN_STATUS_ARCHIVED,
}

CAMPAIGN_CREATEABLE_STATUSES = {
    CAMPAIGN_STATUS_DRAFT,
    CAMPAIGN_STATUS_ACTIVE,
}

CAMPAIGN_STATUS_TRANSITIONS = {
    CAMPAIGN_STATUS_DRAFT: {CAMPAIGN_STATUS_ACTIVE},
    CAMPAIGN_STATUS_ACTIVE: {CAMPAIGN_STATUS_CLOSED, CAMPAIGN_STATUS_DRAFT},
    CAMPAIGN_STATUS_CLOSED: {CAMPAIGN_STATUS_ARCHIVED, CAMPAIGN_STATUS_ACTIVE},
    CAMPAIGN_STATUS_ARCHIVED: {
        CAMPAIGN_STATUS_CLOSED,
        CAMPAIGN_STATUS_ACTIVE,
        CAMPAIGN_STATUS_DRAFT,
    },
}
