from __future__ import annotations

APP_ADMIN_ROLE = "APP_ADMIN"
APP_USER_ROLE = "APP_USER"

CAMPAIGN_MANAGER_ROLE = "CAMPAIGN_MANAGER"
RECIPIENT_COORDINATOR_ROLE = "RECIPIENT_COORDINATOR"
DONATION_ENTRY_ROLE = "DONATION_ENTRY"
GIFT_CHECKIN_ROLE = "GIFT_CHECKIN"
VOLUNTEER_VIEWER_ROLE = "VOLUNTEER_VIEWER"

CAMPAIGN_VIEW_CAPABILITY = "campaign.view"
CAMPAIGN_ADMIN_CAPABILITY = "campaign.admin"
CAMPAIGN_RECIPIENTS_VIEW_CAPABILITY = "campaign.recipients.view"
CAMPAIGN_RECIPIENTS_EDIT_CAPABILITY = "campaign.recipients.edit"
CAMPAIGN_DONATIONS_VIEW_CAPABILITY = "campaign.donations.view"
CAMPAIGN_DONATIONS_EDIT_CAPABILITY = "campaign.donations.edit"
CAMPAIGN_GIFTS_CHECK_IN_CAPABILITY = "campaign.gifts.check_in"
CAMPAIGN_GIFTS_WRAP_CAPABILITY = "campaign.gifts.wrap"
CAMPAIGN_SPONSORS_VIEW_CAPABILITY = "campaign.sponsors.view"
CAMPAIGN_SPONSORS_MANAGE_CAPABILITY = "campaign.sponsors.manage"
CAMPAIGN_REPORTS_VIEW_CAPABILITY = "campaign.reports.view"
CAMPAIGN_PICKUPS_MANAGE_CAPABILITY = "campaign.pickups.manage"

_LEGACY_APP_ROLE_ALIASES = {
    "ADMIN": APP_ADMIN_ROLE,
    "COORDINATOR": APP_USER_ROLE,
    "VOLUNTEER": APP_USER_ROLE,
    APP_ADMIN_ROLE: APP_ADMIN_ROLE,
    APP_USER_ROLE: APP_USER_ROLE,
}

ALL_CAMPAIGN_CAPABILITIES = frozenset(
    {
        CAMPAIGN_VIEW_CAPABILITY,
        CAMPAIGN_ADMIN_CAPABILITY,
        CAMPAIGN_RECIPIENTS_VIEW_CAPABILITY,
        CAMPAIGN_RECIPIENTS_EDIT_CAPABILITY,
        CAMPAIGN_DONATIONS_VIEW_CAPABILITY,
        CAMPAIGN_DONATIONS_EDIT_CAPABILITY,
        CAMPAIGN_GIFTS_CHECK_IN_CAPABILITY,
        CAMPAIGN_GIFTS_WRAP_CAPABILITY,
        CAMPAIGN_SPONSORS_VIEW_CAPABILITY,
        CAMPAIGN_SPONSORS_MANAGE_CAPABILITY,
        CAMPAIGN_REPORTS_VIEW_CAPABILITY,
        CAMPAIGN_PICKUPS_MANAGE_CAPABILITY,
    }
)

CAMPAIGN_ROLE_CAPABILITIES = {
    CAMPAIGN_MANAGER_ROLE: ALL_CAMPAIGN_CAPABILITIES,
    RECIPIENT_COORDINATOR_ROLE: frozenset(
        {
            CAMPAIGN_VIEW_CAPABILITY,
            CAMPAIGN_RECIPIENTS_VIEW_CAPABILITY,
            CAMPAIGN_RECIPIENTS_EDIT_CAPABILITY,
            CAMPAIGN_SPONSORS_VIEW_CAPABILITY,
            CAMPAIGN_REPORTS_VIEW_CAPABILITY,
        }
    ),
    DONATION_ENTRY_ROLE: frozenset(
        {
            CAMPAIGN_VIEW_CAPABILITY,
            CAMPAIGN_DONATIONS_VIEW_CAPABILITY,
            CAMPAIGN_DONATIONS_EDIT_CAPABILITY,
        }
    ),
    GIFT_CHECKIN_ROLE: frozenset(
        {
            CAMPAIGN_VIEW_CAPABILITY,
            CAMPAIGN_GIFTS_CHECK_IN_CAPABILITY,
            CAMPAIGN_GIFTS_WRAP_CAPABILITY,
        }
    ),
    VOLUNTEER_VIEWER_ROLE: frozenset({CAMPAIGN_VIEW_CAPABILITY}),
}


def normalize_app_role(value: str | None) -> str:
    normalized = (value or "").strip().upper()
    return _LEGACY_APP_ROLE_ALIASES.get(normalized, APP_USER_ROLE)


def normalize_campaign_role_key(value: str | None) -> str:
    return (value or "").strip().upper()


def get_capabilities_for_campaign_role(role_key: str | None) -> frozenset[str]:
    return CAMPAIGN_ROLE_CAPABILITIES.get(normalize_campaign_role_key(role_key), frozenset())
