import { render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { ReportsPage } from '@/pages/ReportsPage';

const mockUseCampaigns = vi.fn();
const mockUseCampaignPeopleWorkspace = vi.fn();

vi.mock('@/features/campaigns/model/campaignContext', () => ({
  useCampaigns: () => mockUseCampaigns(),
}));

vi.mock('@/features/campaigns/model/useCampaignPeopleWorkspace', () => ({
  useCampaignPeopleWorkspace: (campaignId: string | null) => mockUseCampaignPeopleWorkspace(campaignId),
}));

describe('ReportsPage', () => {
  beforeEach(() => {
    mockUseCampaigns.mockReset();
    mockUseCampaignPeopleWorkspace.mockReset();
  });

  it('renders people reporting for the selected campaign', () => {
    mockUseCampaigns.mockReturnValue({
      campaigns: [{ id: 'campaign-1', name: 'Holiday 2026' }],
      selectedCampaign: { id: 'campaign-1', name: 'Holiday 2026' },
      selectedCampaignId: 'campaign-1',
      isLoading: false,
    });
    mockUseCampaignPeopleWorkspace.mockReturnValue({
      workspace: {
        campaignId: 'campaign-1',
        counts: {
          groupCount: 3,
          activeGroupCount: 2,
          householdCount: 2,
          organizationCount: 1,
          recipientCount: 4,
          childCount: 2,
          adultCount: 2,
          wishlistCount: 3,
          openItemCount: 5,
          sponsoredItemCount: 1,
          fulfilledItemCount: 0,
          readyForPickupItemCount: 1,
          pickedUpItemCount: 0,
          groupsWithPickupContactsCount: 1,
          groupsMissingPrimaryContactCount: 1,
          adultsWithDirectContactCount: 1,
        },
        groups: [
          {
            id: 'group-1',
            campaignId: 'campaign-1',
            groupType: 'HOUSEHOLD',
            groupName: 'Jones Family',
            organizationType: null,
            programAbbreviation: null,
            intakeSource: null,
            externalReference: null,
            notes: null,
            status: 'ACTIVE',
            addressLine1: null,
            addressLine2: null,
            city: null,
            state: null,
            postalCode: null,
            primaryContact: null,
            contacts: [],
            authorizedPickupContacts: [],
            recipientCount: 2,
            workflowSummary: {
              itemCount: 1,
              sponsoredItemCount: 0,
              fulfilledItemCount: 0,
              readyForPickupItemCount: 0,
              pickedUpItemCount: 0,
              openItemCount: 1,
            },
            recipients: [],
            createdAt: null,
            updatedAt: null,
          },
          {
            id: 'group-2',
            campaignId: 'campaign-1',
            groupType: 'ORGANIZATION',
            groupName: 'Maple Grove',
            organizationType: 'SENIOR_PROGRAM',
            programAbbreviation: 'MG',
            intakeSource: null,
            externalReference: null,
            notes: null,
            status: 'ACTIVE',
            addressLine1: null,
            addressLine2: null,
            city: null,
            state: null,
            postalCode: null,
            primaryContact: {
              id: 'contact-1',
              recipientGroupId: 'group-2',
              displayName: 'Ava Nurse',
              contactRole: 'STAFF',
              relationshipLabel: null,
              firstName: 'Ava',
              lastName: 'Nurse',
              email: null,
              phone: '555-0000',
              preferredContact: 'PHONE',
              isPrimary: true,
              canPickUp: true,
              isEmergencyContact: false,
              notes: null,
              createdAt: null,
              updatedAt: null,
            },
            contacts: [],
            authorizedPickupContacts: [
              {
                id: 'contact-1',
                recipientGroupId: 'group-2',
                displayName: 'Ava Nurse',
                contactRole: 'STAFF',
                relationshipLabel: null,
                firstName: 'Ava',
                lastName: 'Nurse',
                email: null,
                phone: '555-0000',
                preferredContact: 'PHONE',
                isPrimary: true,
                canPickUp: true,
                isEmergencyContact: false,
                notes: null,
                createdAt: null,
                updatedAt: null,
              },
            ],
            recipientCount: 2,
            workflowSummary: {
              itemCount: 1,
              sponsoredItemCount: 1,
              fulfilledItemCount: 0,
              readyForPickupItemCount: 1,
              pickedUpItemCount: 0,
              openItemCount: 0,
            },
            recipients: [],
            createdAt: null,
            updatedAt: null,
          },
        ],
        recipients: [
          {
            id: 'recipient-1',
            campaignId: 'campaign-1',
            recipientGroupId: 'group-1',
            recipientKind: 'CHILD',
            programType: 'CHILD_FAMILY',
            privacyLevel: 'FULL_NAME',
            displayLabel: 'Sam Jones',
            programRecipientNumber: null,
            programRecipientId: null,
            firstName: 'Sam',
            lastName: 'Jones',
            birthYear: null,
            age: 8,
            gender: 'M',
            addressLine1: null,
            addressLine2: null,
            city: null,
            state: null,
            postalCode: null,
            directEmail: null,
            directPhone: null,
            facilityRoom: null,
            subgroupLabel: null,
            mobilityNotes: null,
            notes: null,
            status: 'ACTIVE',
            group: { id: 'group-1', groupName: 'Jones Family', groupType: 'HOUSEHOLD', organizationType: null, status: 'ACTIVE' },
            wishlist: {
              id: 'wishlist-1',
              campaignId: 'campaign-1',
              recipientId: 'recipient-1',
              wishlistStatus: 'READY',
              intakeMethod: null,
              submittedAt: null,
              intakeCompletedByContactId: null,
              intakeCompletedByContact: null,
              notes: null,
              items: [
                {
                  id: 'item-1',
                  wishlistId: 'wishlist-1',
                  category: null,
                  itemType: 'GIFT',
                  description: 'Toy',
                  size: null,
                  qtyRequested: 1,
                  priority: 'HIGH',
                  estCostCents: null,
                  allowSubstitute: true,
                  doNotSubstituteReason: null,
                  recipientNote: null,
                  status: 'OPEN',
                  qtyFulfilled: 0,
                  notes: null,
                  giftWorkflow: {
                    sponsorshipStatus: 'UNSPONSORED',
                    sponsorshipId: null,
                    qtyCommitted: 0,
                    qtyFulfilled: 0,
                    remainingQty: 1,
                    isFullyFulfilled: false,
                    isPickedUp: false,
                    pickedUpAt: null,
                    pickedUpByContactId: null,
                    labelCode: 'A',
                    labelVersion: 1,
                    labelLastPrintedAt: null,
                    labelPrintCount: 0,
                  },
                  createdAt: null,
                  updatedAt: null,
                },
              ],
              createdAt: null,
              updatedAt: null,
            },
            workflowSummary: {
              itemCount: 1,
              sponsoredItemCount: 0,
              fulfilledItemCount: 0,
              readyForPickupItemCount: 0,
              pickedUpItemCount: 0,
              openItemCount: 1,
            },
            createdAt: null,
            updatedAt: null,
          },
          {
            id: 'recipient-2',
            campaignId: 'campaign-1',
            recipientGroupId: 'group-2',
            recipientKind: 'ADULT',
            programType: 'ORGANIZATION_ADULT',
            privacyLevel: 'FULL_NAME',
            displayLabel: 'Mary Smith',
            programRecipientNumber: 1,
            programRecipientId: 'MG-001',
            firstName: 'Mary',
            lastName: 'Smith',
            birthYear: null,
            age: 81,
            gender: 'F',
            addressLine1: null,
            addressLine2: null,
            city: null,
            state: null,
            postalCode: null,
            directEmail: 'mary@example.com',
            directPhone: '555-1111',
            facilityRoom: '214B',
            subgroupLabel: null,
            mobilityNotes: null,
            notes: null,
            status: 'ACTIVE',
            group: { id: 'group-2', groupName: 'Maple Grove', groupType: 'ORGANIZATION', organizationType: 'SENIOR_PROGRAM', status: 'ACTIVE' },
            wishlist: {
              id: 'wishlist-2',
              campaignId: 'campaign-1',
              recipientId: 'recipient-2',
              wishlistStatus: 'DRAFT',
              intakeMethod: null,
              submittedAt: null,
              intakeCompletedByContactId: null,
              intakeCompletedByContact: null,
              notes: null,
              items: [],
              createdAt: null,
              updatedAt: null,
            },
            workflowSummary: {
              itemCount: 0,
              sponsoredItemCount: 0,
              fulfilledItemCount: 0,
              readyForPickupItemCount: 0,
              pickedUpItemCount: 0,
              openItemCount: 0,
            },
            createdAt: null,
            updatedAt: null,
          },
          {
            id: 'recipient-3',
            campaignId: 'campaign-1',
            recipientGroupId: 'group-2',
            recipientKind: 'ADULT',
            programType: 'ORGANIZATION_ADULT',
            privacyLevel: 'FULL_NAME',
            displayLabel: 'James Hall',
            firstName: 'James',
            lastName: 'Hall',
            birthYear: null,
            age: 78,
            gender: 'M',
            addressLine1: null,
            addressLine2: null,
            city: null,
            state: null,
            postalCode: null,
            directEmail: null,
            directPhone: null,
            facilityRoom: null,
            subgroupLabel: null,
            mobilityNotes: null,
            notes: null,
            status: 'ACTIVE',
            group: { id: 'group-2', groupName: 'Maple Grove', groupType: 'ORGANIZATION', organizationType: 'SENIOR_PROGRAM', status: 'ACTIVE' },
            wishlist: null,
            workflowSummary: {
              itemCount: 0,
              sponsoredItemCount: 0,
              fulfilledItemCount: 0,
              readyForPickupItemCount: 0,
              pickedUpItemCount: 0,
              openItemCount: 0,
            },
            createdAt: null,
            updatedAt: null,
          },
        ],
        filters: {
          groupTypes: ['HOUSEHOLD', 'ORGANIZATION'],
          groupStatuses: ['ACTIVE'],
          programTypes: ['CHILD_FAMILY', 'ORGANIZATION_ADULT'],
          recipientKinds: ['CHILD', 'ADULT'],
          recipientStatuses: ['ACTIVE'],
        },
      },
      isLoading: false,
      error: null,
    });

    render(
      <MemoryRouter>
        <ReportsPage />
      </MemoryRouter>
    );

    expect(screen.getByText(/people reports/i)).toBeInTheDocument();
    expect(screen.getByText(/holiday 2026/i)).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: /group mix/i })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: /wishlist readiness/i })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: /gift workflow/i })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: /pickup coordination/i })).toBeInTheDocument();
    expect(screen.getByText(/ready for pickup/i)).toBeInTheDocument();
    expect(screen.getByText(/missing wishlist/i)).toBeInTheDocument();
    expect(screen.getByText(/sam jones/i)).toBeInTheDocument();
    expect(screen.getByRole('link', { name: /open directory/i })).toHaveAttribute(
      'href',
      '/campaigns/campaign-1/people/directory'
    );
  });
});
