from __future__ import annotations

CAMPAIGN_MEMBER_TYPE_STAFF = "staff"
CAMPAIGN_MEMBER_TYPE_VOLUNTEER = "volunteer"
CAMPAIGN_MEMBER_TYPE_CONTACT = "contact"
CAMPAIGN_MEMBER_TYPE_EXTERNAL = "external"

CAMPAIGN_MEMBER_TYPES = (
    CAMPAIGN_MEMBER_TYPE_STAFF,
    CAMPAIGN_MEMBER_TYPE_VOLUNTEER,
    CAMPAIGN_MEMBER_TYPE_CONTACT,
    CAMPAIGN_MEMBER_TYPE_EXTERNAL,
)

APP_ACCESS_STATUS_NONE = "none"
APP_ACCESS_STATUS_LINKED = "linked"
APP_ACCESS_STATUS_INVITED = "invited"
APP_ACCESS_STATUS_ACTIVE = "active"

CAMPAIGN_MEMBER_APP_ACCESS_STATUSES = (
    APP_ACCESS_STATUS_NONE,
    APP_ACCESS_STATUS_LINKED,
    APP_ACCESS_STATUS_INVITED,
    APP_ACCESS_STATUS_ACTIVE,
)
