RECIPIENT_GROUP_TYPE_HOUSEHOLD = "HOUSEHOLD"
RECIPIENT_GROUP_TYPE_ORGANIZATION = "ORGANIZATION"

RECIPIENT_ORGANIZATION_TYPE_NURSING_HOME = "NURSING_HOME"
RECIPIENT_ORGANIZATION_TYPE_ORPHANAGE = "ORPHANAGE"
RECIPIENT_ORGANIZATION_TYPE_SENIOR_PROGRAM = "SENIOR_PROGRAM"
RECIPIENT_ORGANIZATION_TYPE_CHILDRENS_HOME = "CHILDRENS_HOME"
RECIPIENT_ORGANIZATION_TYPE_PARTNER_ORG = "PARTNER_ORG"
RECIPIENT_ORGANIZATION_TYPE_OTHER = "OTHER"

GROUP_CONTACT_ROLE_PARENT = "PARENT"
GROUP_CONTACT_ROLE_GUARDIAN = "GUARDIAN"
GROUP_CONTACT_ROLE_SOCIAL_WORKER = "SOCIAL_WORKER"
GROUP_CONTACT_ROLE_STAFF = "STAFF"
GROUP_CONTACT_ROLE_COORDINATOR = "COORDINATOR"
GROUP_CONTACT_ROLE_OTHER = "OTHER"

PREFERRED_CONTACT_EMAIL = "EMAIL"
PREFERRED_CONTACT_PHONE = "PHONE"
PREFERRED_CONTACT_TEXT = "TEXT"
PREFERRED_CONTACT_NONE = "NONE"

RECIPIENT_KIND_CHILD = "CHILD"
RECIPIENT_KIND_ADULT = "ADULT"

RECIPIENT_AGE_UNIT_MONTHS = "MONTHS"
RECIPIENT_AGE_UNIT_YEARS = "YEARS"

RECIPIENT_PROGRAM_TYPE_CHILD_FAMILY = "CHILD_FAMILY"
RECIPIENT_PROGRAM_TYPE_ORGANIZATION_CHILD = "ORGANIZATION_CHILD"
RECIPIENT_PROGRAM_TYPE_ORGANIZATION_ADULT = "ORGANIZATION_ADULT"

RECIPIENT_PRIVACY_LEVEL_ANONYMOUS = "ANONYMOUS"
RECIPIENT_PRIVACY_LEVEL_INITIALS = "INITIALS"
RECIPIENT_PRIVACY_LEVEL_FULL_NAME = "FULL_NAME"

RECIPIENT_STATUS_ACTIVE = "ACTIVE"
RECIPIENT_STATUS_INACTIVE = "INACTIVE"

RECIPIENT_GROUP_STATUS_ACTIVE = "ACTIVE"
RECIPIENT_GROUP_STATUS_INACTIVE = "INACTIVE"
RECIPIENT_GROUP_STATUS_ARCHIVED = "ARCHIVED"

WISHLIST_STATUS_DRAFT = "DRAFT"
WISHLIST_STATUS_READY = "READY"
WISHLIST_STATUS_LOCKED = "LOCKED"

WISHLIST_INTAKE_METHOD_PHONE = "PHONE"
WISHLIST_INTAKE_METHOD_FORM = "FORM"
WISHLIST_INTAKE_METHOD_STAFF_ENTRY = "STAFF_ENTRY"
WISHLIST_INTAKE_METHOD_IMPORT = "IMPORT"
WISHLIST_INTAKE_METHOD_OTHER = "OTHER"

WISHLIST_ITEM_TYPE_GIFT = "GIFT"
WISHLIST_ITEM_TYPE_CLOTHING = "CLOTHING"
WISHLIST_ITEM_TYPE_ESSENTIAL = "ESSENTIAL"
WISHLIST_ITEM_TYPE_GIFT_CARD = "GIFT_CARD"
WISHLIST_ITEM_TYPE_EXPERIENCE = "EXPERIENCE"
WISHLIST_ITEM_TYPE_OTHER = "OTHER"
