SPONSOR_SOURCE_STAFF_ENTRY = "STAFF_ENTRY"
SPONSOR_SOURCE_PUBLIC_QR = "PUBLIC_QR"
SPONSOR_SOURCE_PUBLIC_LINK = "PUBLIC_LINK"
SPONSOR_SOURCE_IMPORT = "IMPORT"
SPONSOR_SOURCE_OTHER = "OTHER"

SPONSOR_SOURCES = (
    SPONSOR_SOURCE_STAFF_ENTRY,
    SPONSOR_SOURCE_PUBLIC_QR,
    SPONSOR_SOURCE_PUBLIC_LINK,
    SPONSOR_SOURCE_IMPORT,
    SPONSOR_SOURCE_OTHER,
)

SPONSORSHIP_STATUS_ACTIVE = "ACTIVE"
SPONSORSHIP_STATUS_COMPLETE = "COMPLETE"
SPONSORSHIP_STATUS_CANCELLED = "CANCELLED"

SPONSORSHIP_STATUSES = (
    SPONSORSHIP_STATUS_ACTIVE,
    SPONSORSHIP_STATUS_COMPLETE,
    SPONSORSHIP_STATUS_CANCELLED,
)

SPONSORSHIP_INTEREST_STATUS_NEW = "NEW"
SPONSORSHIP_INTEREST_STATUS_CONTACTED = "CONTACTED"
SPONSORSHIP_INTEREST_STATUS_RESPONDED = "RESPONDED"
SPONSORSHIP_INTEREST_STATUS_COMMITTED = "COMMITTED"
SPONSORSHIP_INTEREST_STATUS_DECLINED = "DECLINED"

SPONSORSHIP_INTEREST_STATUSES = (
    SPONSORSHIP_INTEREST_STATUS_NEW,
    SPONSORSHIP_INTEREST_STATUS_CONTACTED,
    SPONSORSHIP_INTEREST_STATUS_RESPONDED,
    SPONSORSHIP_INTEREST_STATUS_COMMITTED,
    SPONSORSHIP_INTEREST_STATUS_DECLINED,
)

SPONSORSHIP_DROP_OFF_STATUS_NOT_STARTED = "NOT_STARTED"
SPONSORSHIP_DROP_OFF_STATUS_SCHEDULED = "SCHEDULED"
SPONSORSHIP_DROP_OFF_STATUS_RECEIVED = "RECEIVED"
SPONSORSHIP_DROP_OFF_STATUS_LATE = "LATE"

SPONSORSHIP_DROP_OFF_STATUSES = (
    SPONSORSHIP_DROP_OFF_STATUS_NOT_STARTED,
    SPONSORSHIP_DROP_OFF_STATUS_SCHEDULED,
    SPONSORSHIP_DROP_OFF_STATUS_RECEIVED,
    SPONSORSHIP_DROP_OFF_STATUS_LATE,
)

SPONSOR_INTERACTION_ORIGIN_MANUAL = "MANUAL"
SPONSOR_INTERACTION_ORIGIN_CAMPAIGN_COMMUNICATION = "CAMPAIGN_COMMUNICATION"
SPONSOR_INTERACTION_ORIGIN_PUBLIC_SIGNUP = "PUBLIC_SIGNUP"
SPONSOR_INTERACTION_ORIGIN_SYSTEM = "SYSTEM"

SPONSOR_INTERACTION_ORIGINS = (
    SPONSOR_INTERACTION_ORIGIN_MANUAL,
    SPONSOR_INTERACTION_ORIGIN_CAMPAIGN_COMMUNICATION,
    SPONSOR_INTERACTION_ORIGIN_PUBLIC_SIGNUP,
    SPONSOR_INTERACTION_ORIGIN_SYSTEM,
)

PENDING_SPONSOR_REGISTRATION_STATUS_PENDING = "PENDING"
PENDING_SPONSOR_REGISTRATION_STATUS_VERIFIED = "VERIFIED"
PENDING_SPONSOR_REGISTRATION_STATUS_EXPIRED = "EXPIRED"
PENDING_SPONSOR_REGISTRATION_STATUS_CANCELLED = "CANCELLED"

PENDING_SPONSOR_REGISTRATION_STATUSES = (
    PENDING_SPONSOR_REGISTRATION_STATUS_PENDING,
    PENDING_SPONSOR_REGISTRATION_STATUS_VERIFIED,
    PENDING_SPONSOR_REGISTRATION_STATUS_EXPIRED,
    PENDING_SPONSOR_REGISTRATION_STATUS_CANCELLED,
)
