CREATE TABLE campaign_milestone_definition (
  id BINARY(16) NOT NULL,
  milestone_key VARCHAR(64) NOT NULL,
  label VARCHAR(255) NOT NULL,
  description TEXT NULL,
  feature_area ENUM('GENERAL','RECIPIENTS','SPONSORS','GIFTS','PICKUP','COMMUNICATIONS') NOT NULL DEFAULT 'GENERAL',
  default_sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  is_system TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_campaign_milestone_definition_key (milestone_key),
  KEY idx_campaign_milestone_definition_key (milestone_key),
  KEY idx_campaign_milestone_definition_active (is_active),
  KEY idx_campaign_milestone_definition_feature_area (feature_area)
);

CREATE TABLE campaign_readiness_rule_definition (
  id BINARY(16) NOT NULL,
  rule_key VARCHAR(120) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  rule_type ENUM('MISSING_MILESTONE') NOT NULL,
  feature_area ENUM('GENERAL','RECIPIENTS','SPONSORS','GIFTS','PICKUP','COMMUNICATIONS') NOT NULL DEFAULT 'GENERAL',
  condition_type ENUM('ALWAYS','CAMPAIGN_FIELD_TRUE','CAMPAIGN_STATUS_IS','FEATURE_ENABLED') NOT NULL DEFAULT 'ALWAYS',
  condition_config_json JSON NULL,
  milestone_key VARCHAR(64) NULL,
  severity ENUM('error','warning','info') NOT NULL,
  category ENUM('blockers','launch_checks','planning_gaps','operational_health') NOT NULL,
  blocking_for_json JSON NOT NULL,
  section VARCHAR(64) NOT NULL,
  action_label VARCHAR(120) NULL,
  message VARCHAR(512) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  is_system TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_campaign_readiness_rule_definition_key (rule_key),
  KEY idx_campaign_readiness_rule_definition_key (rule_key),
  KEY idx_campaign_readiness_rule_active_type (is_active, rule_type),
  KEY idx_campaign_readiness_rule_milestone (milestone_key),
  KEY idx_campaign_readiness_rule_feature_area (feature_area)
);

INSERT INTO campaign_milestone_definition
  (id, milestone_key, label, description, feature_area, default_sort_order, is_active, is_system)
VALUES
  (UUID_TO_BIN('00000000-0000-0000-0000-000000000101', true), 'registration_open', 'Registration Opens', 'Recipient registration opens for the campaign.', 'RECIPIENTS', 1, 1, 1),
  (UUID_TO_BIN('00000000-0000-0000-0000-000000000102', true), 'registration_close', 'Registration Closes', 'Recipient registration closes for the campaign.', 'RECIPIENTS', 2, 1, 1),
  (UUID_TO_BIN('00000000-0000-0000-0000-000000000103', true), 'sponsor_registration_start', 'Sponsor Registration Starts', 'Public sponsor registration opens for the campaign.', 'SPONSORS', 3, 1, 1),
  (UUID_TO_BIN('00000000-0000-0000-0000-000000000104', true), 'sponsor_registration_end', 'Sponsor Registration Ends', 'Public sponsor registration closes for the campaign.', 'SPONSORS', 4, 1, 1),
  (UUID_TO_BIN('00000000-0000-0000-0000-000000000105', true), 'sponsor_outreach_start', 'Sponsor Outreach Starts', 'Sponsor outreach begins for the campaign.', 'SPONSORS', 5, 1, 1),
  (UUID_TO_BIN('00000000-0000-0000-0000-000000000106', true), 'gift_intake_start', 'Gift Intake Starts', 'Gift turn-in begins for the campaign.', 'GIFTS', 6, 1, 1),
  (UUID_TO_BIN('00000000-0000-0000-0000-000000000107', true), 'gift_intake_end', 'Gift Intake Ends', 'Gift turn-in deadline for the campaign.', 'GIFTS', 7, 1, 1),
  (UUID_TO_BIN('00000000-0000-0000-0000-000000000108', true), 'pickup_start', 'Pickup Window Opens', 'Pickup window opens for the campaign.', 'PICKUP', 8, 1, 1),
  (UUID_TO_BIN('00000000-0000-0000-0000-000000000109', true), 'pickup_end', 'Pickup Window Closes', 'Pickup window closes for the campaign.', 'PICKUP', 9, 1, 1),
  (UUID_TO_BIN('00000000-0000-0000-0000-000000000110', true), 'campaign_close', 'Campaign Closes', 'Campaign close milestone.', 'GENERAL', 10, 1, 1);

INSERT INTO campaign_readiness_rule_definition
  (
    id,
    rule_key,
    name,
    description,
    rule_type,
    feature_area,
    condition_type,
    condition_config_json,
    milestone_key,
    severity,
    category,
    blocking_for_json,
    section,
    action_label,
    message,
    is_active,
    is_system
  )
VALUES
  (
    UUID_TO_BIN('00000000-0000-0000-0000-000000000201', true),
    'missing_public_sponsor_registration_start',
    'Missing Sponsor Registration Start',
    'Requires a sponsor registration start date when public sponsor signup is enabled.',
    'MISSING_MILESTONE',
    'SPONSORS',
    'CAMPAIGN_FIELD_TRUE',
    JSON_OBJECT('field', 'public_sponsor_signup_enabled'),
    'sponsor_registration_start',
    'error',
    'blockers',
    JSON_ARRAY('activate', 'operations'),
    'schedule',
    'Open Schedule',
    'Public sponsor signup is enabled, but the sponsor registration start milestone is missing.',
    1,
    1
  ),
  (
    UUID_TO_BIN('00000000-0000-0000-0000-000000000202', true),
    'missing_public_sponsor_registration_end',
    'Missing Sponsor Registration End',
    'Requires a sponsor registration end date when public sponsor signup is enabled.',
    'MISSING_MILESTONE',
    'SPONSORS',
    'CAMPAIGN_FIELD_TRUE',
    JSON_OBJECT('field', 'public_sponsor_signup_enabled'),
    'sponsor_registration_end',
    'error',
    'blockers',
    JSON_ARRAY('activate', 'operations'),
    'schedule',
    'Open Schedule',
    'Public sponsor signup is enabled, but the sponsor registration end milestone is missing.',
    1,
    1
  ),
  (
    UUID_TO_BIN('00000000-0000-0000-0000-000000000203', true),
    'missing_public_sponsor_gift_turn_in',
    'Missing Gift Turn-In Deadline',
    'Requires a gift turn-in deadline when public sponsor signup is enabled.',
    'MISSING_MILESTONE',
    'SPONSORS',
    'CAMPAIGN_FIELD_TRUE',
    JSON_OBJECT('field', 'public_sponsor_signup_enabled'),
    'gift_intake_end',
    'error',
    'blockers',
    JSON_ARRAY('activate', 'operations'),
    'schedule',
    'Open Schedule',
    'Public sponsor signup is enabled, but the gift turn-in deadline milestone is missing.',
    1,
    1
  ),
  (
    UUID_TO_BIN('00000000-0000-0000-0000-000000000204', true),
    'missing_required_milestone_registration_open',
    'Missing Registration Open',
    'Warns when the campaign registration open milestone is missing.',
    'MISSING_MILESTONE',
    'RECIPIENTS',
    'ALWAYS',
    NULL,
    'registration_open',
    'warning',
    'launch_checks',
    JSON_ARRAY('activate'),
    'schedule',
    'Open Schedule',
    'Add the Registration Opens milestone date.',
    1,
    1
  ),
  (
    UUID_TO_BIN('00000000-0000-0000-0000-000000000205', true),
    'missing_required_milestone_registration_close',
    'Missing Registration Close',
    'Warns when the campaign registration close milestone is missing.',
    'MISSING_MILESTONE',
    'RECIPIENTS',
    'ALWAYS',
    NULL,
    'registration_close',
    'warning',
    'launch_checks',
    JSON_ARRAY('activate'),
    'schedule',
    'Open Schedule',
    'Add the Registration Closes milestone date.',
    1,
    1
  ),
  (
    UUID_TO_BIN('00000000-0000-0000-0000-000000000206', true),
    'missing_required_milestone_sponsor_outreach_start',
    'Missing Sponsor Outreach Start',
    'Warns when the campaign sponsor outreach start milestone is missing.',
    'MISSING_MILESTONE',
    'SPONSORS',
    'ALWAYS',
    NULL,
    'sponsor_outreach_start',
    'warning',
    'launch_checks',
    JSON_ARRAY('activate'),
    'schedule',
    'Open Schedule',
    'Add the Sponsor Outreach Starts milestone date.',
    1,
    1
  ),
  (
    UUID_TO_BIN('00000000-0000-0000-0000-000000000207', true),
    'missing_required_milestone_gift_intake_start',
    'Missing Gift Intake Start',
    'Warns when the campaign gift intake start milestone is missing.',
    'MISSING_MILESTONE',
    'GIFTS',
    'ALWAYS',
    NULL,
    'gift_intake_start',
    'warning',
    'launch_checks',
    JSON_ARRAY('activate'),
    'schedule',
    'Open Schedule',
    'Add the Gift Intake Starts milestone date.',
    1,
    1
  ),
  (
    UUID_TO_BIN('00000000-0000-0000-0000-000000000208', true),
    'missing_required_milestone_gift_intake_end',
    'Missing Gift Intake End',
    'Warns when the campaign gift intake end milestone is missing.',
    'MISSING_MILESTONE',
    'GIFTS',
    'ALWAYS',
    NULL,
    'gift_intake_end',
    'warning',
    'launch_checks',
    JSON_ARRAY('activate'),
    'schedule',
    'Open Schedule',
    'Add the Gift Intake Ends milestone date.',
    1,
    1
  ),
  (
    UUID_TO_BIN('00000000-0000-0000-0000-000000000209', true),
    'missing_required_milestone_pickup_start',
    'Missing Pickup Start',
    'Warns when the campaign pickup start milestone is missing.',
    'MISSING_MILESTONE',
    'PICKUP',
    'ALWAYS',
    NULL,
    'pickup_start',
    'warning',
    'launch_checks',
    JSON_ARRAY('activate'),
    'schedule',
    'Open Schedule',
    'Add the Pickup Window Opens milestone date.',
    1,
    1
  ),
  (
    UUID_TO_BIN('00000000-0000-0000-0000-000000000210', true),
    'missing_required_milestone_pickup_end',
    'Missing Pickup End',
    'Warns when the campaign pickup end milestone is missing.',
    'MISSING_MILESTONE',
    'PICKUP',
    'ALWAYS',
    NULL,
    'pickup_end',
    'warning',
    'launch_checks',
    JSON_ARRAY('activate'),
    'schedule',
    'Open Schedule',
    'Add the Pickup Window Closes milestone date.',
    1,
    1
  ),
  (
    UUID_TO_BIN('00000000-0000-0000-0000-000000000211', true),
    'missing_required_milestone_campaign_close',
    'Missing Campaign Close',
    'Warns when the campaign close milestone is missing.',
    'MISSING_MILESTONE',
    'GENERAL',
    'ALWAYS',
    NULL,
    'campaign_close',
    'warning',
    'launch_checks',
    JSON_ARRAY('activate'),
    'schedule',
    'Open Schedule',
    'Add the Campaign Closes milestone date.',
    1,
    1
  );
