CREATE TABLE app_user_settings (
  user_id BINARY(16) NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'America/Chicago',
  date_format ENUM('MM_DD_YYYY','YYYY_MM_DD') NOT NULL DEFAULT 'MM_DD_YYYY',
  default_landing_page ENUM('DASHBOARD','CAMPAIGNS','CURRENT_CAMPAIGN') NOT NULL DEFAULT 'DASHBOARD',
  email_notifications_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  CONSTRAINT fk_app_user_settings_user
    FOREIGN KEY (user_id) REFERENCES app_user(id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
