from __future__ import annotations

from app.features.ask.schemas import ReportMetric


REPORT_METRICS: tuple[ReportMetric, ...] = (
    ReportMetric(
        metric_key="recipients_needing_sponsors",
        title="Recipients Needing Sponsors",
        subject="recipients",
        phrases=(
            "recipients need sponsors",
            "children need sponsors",
            "still need sponsors",
            "still needing sponsors",
            "without sponsors",
            "not sponsored",
        ),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_recipients_needing_sponsors",
    ),
    ReportMetric(
        metric_key="recipients_needing_gifts",
        title="Recipients Needing Gifts",
        subject="recipients",
        phrases=("recipients need gifts", "people still needing gifts", "children need gifts", "still needing gifts", "not fulfilled"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_recipients_needing_gifts",
    ),
    ReportMetric(
        metric_key="committed_gifts_not_received",
        title="Committed Gifts Not Received",
        subject="wishlist_items",
        phrases=("committed not received", "committed gifts not received", "sponsored but not received", "not turned in", "turn in"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_committed_gifts_not_received",
    ),
    ReportMetric(
        metric_key="ready_gifts_not_distributed",
        title="Ready Gifts Not Distributed",
        subject="wishlist_items",
        phrases=(
            "ready not distributed",
            "ready gifts not distributed",
            "ready but not picked up",
            "ready but not given",
            "ready for pickup",
            "ready for distribution",
            "gifts ready for pickup",
            "gifts ready for distribution",
        ),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_ready_gifts_not_distributed",
    ),
    ReportMetric(
        metric_key="recipients_not_fulfilled",
        title="Recipients Not Fulfilled",
        subject="recipients",
        phrases=(
            "show recipients not fulfilled",
            "recipients not fulfilled",
            "children not fulfilled",
            "people not fulfilled",
            "not fully fulfilled",
            "not completed",
            "not complete",
        ),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_recipients_not_fulfilled",
    ),
    ReportMetric(
        metric_key="overdue_sponsor_gifts",
        title="Overdue Sponsor Gifts",
        subject="sponsors",
        phrases=(
            "overdue gifts",
            "late gifts",
            "gifts overdue",
            "gifts are overdue",
            "past due gifts",
            "past due sponsors",
            "sponsors late with gifts",
        ),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_overdue_sponsor_gifts",
    ),
    ReportMetric(
        metric_key="sponsors_with_unreceived_gifts",
        title="Sponsors With Unreceived Gifts",
        subject="sponsors",
        phrases=(
            "sponsors have not turned in gifts",
            "sponsors with unreceived gifts",
            "sponsors with gifts not received",
            "sponsors who have not turned in gifts",
            "sponsors not turned in gifts",
            "sponsors still owe gifts",
            "sponsor gifts not received",
        ),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_sponsors_with_unreceived_gifts",
    ),
    ReportMetric(
        metric_key="exception_gifts",
        title="Gift Exceptions",
        subject="wishlist_items",
        phrases=(
            "gift exceptions",
            "gifts with exceptions",
            "exception gifts",
            "problem gifts",
            "gifts with problems",
        ),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_exception_gifts",
    ),
    ReportMetric(
        metric_key="pending_public_sponsor_registrations",
        title="Pending Public Sponsor Registrations",
        subject="sponsors",
        phrases=(
            "pending public registrations",
            "pending sponsor registrations",
            "unverified sponsor registrations",
            "sponsors not verified",
            "public signups pending",
            "public sign ups pending",
        ),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_pending_public_sponsor_registrations",
    ),
    ReportMetric(
        metric_key="popular_gifts_by_gender",
        title="Popular Gifts By Gender",
        subject="wishlist_items",
        phrases=(
            "most popular gifts by gender",
            "popular gifts by gender",
            "top gifts by gender",
            "top 5 gifts by gender",
            "what gifts are most popular",
        ),
        intents=("list", "count"),
        required_capability="campaign.reports.view",
        executor="execute_popular_gifts_by_gender",
    ),
    ReportMetric(
        metric_key="recipients_sponsored_by_sponsor",
        title="Recipients Sponsored By Sponsor",
        subject="sponsors",
        phrases=(
            "recipients sponsored by sponsor",
            "number of recipients sponsored by sponsor",
            "how many recipients each sponsor has",
            "how many people each sponsor sponsored",
            "sponsor recipient counts",
        ),
        intents=("list", "count"),
        required_capability="campaign.reports.view",
        executor="execute_recipients_sponsored_by_sponsor",
    ),
    ReportMetric(
        metric_key="unsponsored_gifts",
        title="Unsponsored Gifts",
        subject="wishlist_items",
        phrases=(
            "unsponsored gifts",
            "gifts without sponsors",
            "wishlist items without sponsors",
            "how many gifts are unsponsored",
            "show unsponsored gifts",
        ),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_unsponsored_gifts",
    ),
    ReportMetric(
        metric_key="recipient_population_summary",
        title="Children And Adults",
        subject="recipients",
        phrases=(
            "number of children",
            "number of adults",
            "children and adults",
            "how many children and adults",
            "recipient population",
        ),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_recipient_population_summary",
    ),
    ReportMetric(
        metric_key="gift_count_summary",
        title="Gift Count",
        subject="wishlist_items",
        phrases=(
            "number of gifts",
            "gift count",
            "how many total gifts",
            "total gifts",
            "total number of gifts",
            "wishlist item count",
        ),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_gift_count_summary",
    ),
    ReportMetric(
        metric_key="continue_where_left_off",
        title="Pick Up Where I Left Off",
        subject="dashboard",
        phrases=(
            "pick up where i left off",
            "continue where i left off",
            "where did i leave off",
            "my recent questions",
            "recent ask activity",
        ),
        intents=("list",),
        required_capability="campaign.view",
        executor="execute_continue_where_left_off",
    ),
    ReportMetric(
        metric_key="open_wishlist_items",
        title="Open Wishlist Items",
        subject="wishlist_items",
        phrases=("open wishlist items", "available wishlist items", "open gifts", "available gifts", "unsponsored gifts"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_open_wishlist_items",
    ),
    ReportMetric(
        metric_key="received_gifts_not_wrapped",
        title="Received Gifts Not Wrapped",
        subject="wishlist_items",
        phrases=("received not wrapped", "received gifts not wrapped", "gifts to wrap", "need wrapping"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_received_gifts_not_wrapped",
    ),
    ReportMetric(
        metric_key="sponsors_without_commitments",
        title="Sponsors Without Commitments",
        subject="sponsors",
        phrases=("sponsors without commitments", "sponsors with no gifts", "sponsors no commitments", "sponsors who have not sponsored"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_sponsors_without_commitments",
    ),
    ReportMetric(
        metric_key="sponsors_needing_follow_up",
        title="Sponsors Needing Follow-Up",
        subject="sponsors",
        phrases=("sponsors needing follow up", "sponsors need follow up", "follow up queue", "who needs follow up", "sponsor follow up"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_sponsors_needing_follow_up",
    ),
    ReportMetric(
        metric_key="unmatched_donated_inventory",
        title="Unmatched Donated Inventory",
        subject="donations",
        phrases=("unmatched donated inventory", "unmatched donations", "unassigned inventory", "donated items not matched"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_unmatched_donated_inventory",
    ),
    ReportMetric(
        metric_key="readiness_blockers",
        title="Readiness Blockers",
        subject="readiness",
        phrases=("readiness blockers", "campaign blockers", "blocked readiness", "what is blocking", "activation blockers"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_readiness_blockers",
    ),
    ReportMetric(
        metric_key="calendar_overdue",
        title="Overdue Calendar Items",
        subject="calendar",
        phrases=(
            "what is overdue",
            "what's overdue",
            "overdue calendar items",
            "overdue campaign dates",
            "past due calendar",
            "past due campaign dates",
        ),
        intents=("list", "count"),
        required_capability="campaign.view",
        executor="execute_calendar_overdue",
    ),
    ReportMetric(
        metric_key="calendar_upcoming",
        title="Upcoming Calendar Items",
        subject="calendar",
        phrases=(
            "what is coming up this week",
            "what's coming up this week",
            "what is coming up",
            "coming up this week",
            "next 7 days",
            "next 30 days",
            "upcoming campaign dates",
            "upcoming calendar items",
        ),
        intents=("list", "count"),
        required_capability="campaign.view",
        executor="execute_calendar_upcoming",
    ),
    ReportMetric(
        metric_key="calendar_missing_dates",
        title="Missing Important Dates",
        subject="calendar",
        phrases=(
            "important dates missing",
            "missing important dates",
            "missing blocker dates",
            "what blocker dates are missing",
            "what dates are missing",
            "missing campaign dates",
        ),
        intents=("list", "count"),
        required_capability="campaign.view",
        executor="execute_calendar_missing_dates",
    ),
    ReportMetric(
        metric_key="calendar_scheduled_communications",
        title="Scheduled Communications",
        subject="calendar",
        phrases=(
            "scheduled communications",
            "what communications are scheduled",
            "what emails are scheduled",
            "scheduled emails",
            "communications on the calendar",
            "emails on the calendar",
        ),
        intents=("list", "count"),
        required_capability="campaign.view",
        executor="execute_calendar_scheduled_communications",
    ),
    ReportMetric(
        metric_key="calendar_sponsor_recruitment_dates",
        title="Sponsor Recruitment Dates",
        subject="calendar",
        phrases=(
            "when does sponsor recruitment start",
            "when does sponsor recruitment end",
            "when is sponsor recruitment",
            "sponsor recruitment dates",
            "sponsor signup dates",
            "sponsor registration dates",
        ),
        intents=("list", "count"),
        required_capability="campaign.view",
        executor="execute_calendar_sponsor_recruitment_dates",
    ),
    ReportMetric(
        metric_key="calendar_gift_turn_in_date",
        title="Gift Turn-In Date",
        subject="calendar",
        phrases=(
            "when is gift turn in",
            "when is gift turn in?",
            "when is gift turn-in",
            "when is gift turn-in?",
            "gift turn in date",
            "gift turn-in date",
            "when are gifts due",
            "when are gifts due?",
            "gift due date",
        ),
        intents=("list", "count"),
        required_capability="campaign.view",
        executor="execute_calendar_gift_turn_in_date",
    ),
    ReportMetric(
        metric_key="calendar_pickup_dates",
        title="Pickup Dates",
        subject="calendar",
        phrases=(
            "when is pickup",
            "when does pickup start",
            "when does pickup end",
            "pickup dates",
            "distribution dates",
        ),
        intents=("list", "count"),
        required_capability="campaign.view",
        executor="execute_calendar_pickup_dates",
    ),
    ReportMetric(
        metric_key="calendar_followups_due",
        title="Sponsor Follow-Ups Due",
        subject="calendar",
        phrases=(
            "who has follow-up due",
            "who has follow up due",
            "sponsor follow-ups due",
            "sponsor follow ups due",
            "follow-ups due",
            "follow ups due",
        ),
        intents=("list", "count"),
        required_capability="campaign.view",
        executor="execute_calendar_followups_due",
    ),
    ReportMetric(
        metric_key="calendar_outside_campaign_window",
        title="Dates Outside Campaign Window",
        subject="calendar",
        phrases=(
            "dates outside campaign window",
            "dates outside the campaign window",
            "dates outside campaign range",
            "dates outside the campaign range",
            "items outside campaign dates",
            "events outside campaign dates",
        ),
        intents=("list", "count"),
        required_capability="campaign.view",
        executor="execute_calendar_outside_campaign_window",
    ),
    ReportMetric(
        metric_key="calendar_attention",
        title="Campaign Calendar Attention",
        subject="calendar",
        phrases=(
            "what is overdue",
            "what's overdue",
            "what needs attention",
            "calendar attention",
            "campaign dates needing attention",
            "important dates missing",
            "missing important dates",
            "missing blocker dates",
            "what blocker dates are missing",
            "what is coming up this week",
            "what's coming up this week",
            "what is coming up",
            "coming up this week",
            "next 7 days",
            "next 30 days",
            "scheduled communications",
            "what communications are scheduled",
            "what emails are scheduled",
            "campaign timeline",
            "campaign calendar",
        ),
        intents=("list", "count"),
        required_capability="campaign.view",
        executor="execute_calendar_attention",
    ),
)
