from __future__ import annotations

from app.features.ask.schemas import ReportMetric


REPORT_METRICS: tuple[ReportMetric, ...] = (
    ReportMetric(
        metric_key="recipients_needing_sponsors",
        title="Recipients Needing Sponsors",
        subject="recipients",
        phrases=(
            "recipients need sponsors",
            "children need sponsors",
            "still need sponsors",
            "still needing sponsors",
            "without sponsors",
            "not sponsored",
        ),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_recipients_needing_sponsors",
    ),
    ReportMetric(
        metric_key="recipients_needing_gifts",
        title="Recipients Needing Gifts",
        subject="recipients",
        phrases=("recipients need gifts", "people still needing gifts", "children need gifts", "still needing gifts", "not fulfilled"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_recipients_needing_gifts",
    ),
    ReportMetric(
        metric_key="committed_gifts_not_received",
        title="Committed Gifts Not Received",
        subject="wishlist_items",
        phrases=("committed not received", "committed gifts not received", "sponsored but not received", "not turned in", "turn in"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_committed_gifts_not_received",
    ),
    ReportMetric(
        metric_key="ready_gifts_not_distributed",
        title="Ready Gifts Not Distributed",
        subject="wishlist_items",
        phrases=("ready not distributed", "ready gifts not distributed", "ready but not picked up", "ready but not given"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_ready_gifts_not_distributed",
    ),
    ReportMetric(
        metric_key="open_wishlist_items",
        title="Open Wishlist Items",
        subject="wishlist_items",
        phrases=("open wishlist items", "available wishlist items", "open gifts", "available gifts", "unsponsored gifts"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_open_wishlist_items",
    ),
    ReportMetric(
        metric_key="received_gifts_not_wrapped",
        title="Received Gifts Not Wrapped",
        subject="wishlist_items",
        phrases=("received not wrapped", "received gifts not wrapped", "gifts to wrap", "need wrapping"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_received_gifts_not_wrapped",
    ),
    ReportMetric(
        metric_key="sponsors_without_commitments",
        title="Sponsors Without Commitments",
        subject="sponsors",
        phrases=("sponsors without commitments", "sponsors with no gifts", "sponsors no commitments", "sponsors who have not sponsored"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_sponsors_without_commitments",
    ),
    ReportMetric(
        metric_key="sponsors_needing_follow_up",
        title="Sponsors Needing Follow-Up",
        subject="sponsors",
        phrases=("sponsors needing follow up", "sponsors need follow up", "follow up queue", "who needs follow up", "sponsor follow up"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_sponsors_needing_follow_up",
    ),
    ReportMetric(
        metric_key="unmatched_donated_inventory",
        title="Unmatched Donated Inventory",
        subject="donations",
        phrases=("unmatched donated inventory", "unmatched donations", "unassigned inventory", "donated items not matched"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_unmatched_donated_inventory",
    ),
    ReportMetric(
        metric_key="readiness_blockers",
        title="Readiness Blockers",
        subject="readiness",
        phrases=("readiness blockers", "campaign blockers", "blocked readiness", "what is blocking", "activation blockers"),
        intents=("count", "list"),
        required_capability="campaign.reports.view",
        executor="execute_readiness_blockers",
    ),
)
